// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VnResoure_Test_Intern_Backend.Models
{
    public partial class KhoaHoc
    {
        public KhoaHoc()
        {
            MonHoc = new HashSet<MonHoc>();
        }

        public int Id { get; set; }
        public string TenKhoaHoc { get; set; }

        public virtual ICollection<MonHoc> MonHoc { get; set; }
    }
}