// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VnResoure_Test_Intern_Backend.Models
{
    public partial class MonHoc
    {
        public int Id { get; set; }
        public string TenMonHoc { get; set; }
        public string MoTa { get; set; }
        public int KhoaHocId { get; set; }

        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}