// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;

namespace VnResoure_Test_Intern_Backend.Models
{
    public partial class VNR_InternShipContext : DbContext
    {
        IConfigurationRoot configuration;
        public VNR_InternShipContext()
        {
            configuration = new ConfigurationBuilder()
               .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
               .AddJsonFile("appsettings.json")
               .Build();
        }

        public VNR_InternShipContext(DbContextOptions<VNR_InternShipContext> options)
            : base(options)
        {
        }

        public virtual DbSet<KhoaHoc> KhoaHoc { get; set; }
        public virtual DbSet<MonHoc> MonHoc { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<KhoaHoc>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.TenKhoaHoc).HasMaxLength(30);
            });

            modelBuilder.Entity<MonHoc>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.KhoaHocId).HasColumnName("KhoaHocID");

                entity.Property(e => e.MoTa).HasMaxLength(100);

                entity.Property(e => e.TenMonHoc).HasMaxLength(100);

                entity.HasOne(d => d.KhoaHoc)
                    .WithMany(p => p.MonHoc)
                    .HasForeignKey(d => d.KhoaHocId)
                    .HasConstraintName("FK_dbo.BaiHat_dbo.TheLoai_TheLoaiID");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}